import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/provider/auth-provider";
import CartContextProvider from "@/provider/cart-provider";
import { ThemeProvider } from "next-themes";
import WishListContextProvider from "@/provider/wishlist-provider";
import Footer from "@/components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <WishListContextProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />
            <div className="pt-5">{children}</div>
            <Footer/>
            <Toaster richColors />
            </ThemeProvider>
            </WishListContextProvider>
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
